---
Version: '2010-09-09'
Description: Template for VPC. EC2 and S3. 
Resources:
  appidDevVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: appidDevVPC 
